### ISSUE TITLE
@sanity/desk-tool [v2.22.2] not compatible with sanity-plugin-schema-inspector 1.4.0

### ISSUE THREAD

**Issue by goose-chartreuse** [andre-brdoch/sanity-plugin-schema-inspector#3]
With the last update of @sanity/desk-tool v2.22.2 some files have been relocated inside the lib of the mentioned package. This seems to happen at least for the following css file `inspectDialog.css` which is not in the router you are currently specifying in your package. 

```
  "dependencies": {
    "@andre-brdoch/sanity-plugin-schema-inspector": "1.4.0",
    "@sanity/base": "2.22.0",
    "@sanity/components": "2.14.0",
    "@sanity/core": "2.22.0",
    "@sanity/default-layout": "2.22.0",
    "@sanity/default-login": "2.22.0",
    "@sanity/desk-tool": "2.22.2",
    "@sanity/google-maps-input": "2.22.0",
    "@sanity/production-preview": "2.15.0",
    "@sanity/vision": "2.22.0",
    "nanoid": "3.1.25",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "4.2.0",
    "sanity-plugin-intl-input": "5.2.1",
    "sanity-plugin-media-library": "1.0.7",
    "sanity-plugin-note-field": "1.1.3",
    "sanity-plugin-seo-tools": "2.2.0",
    "styled-components": "^5.3.3",
    "typescript": "4.4.2"
  },
  "devDependencies": {
    "@sanity/cli": "2.22.0",
    "@typescript-eslint/eslint-plugin": "5.4.0",
    "@typescript-eslint/parser": "5.4.0",
    "eslint": "7.32.0",
    "eslint-config-sanity": "5.1.0",
    "eslint-plugin-react": "7.27.1",
    "prettier": "2.3.2",
    "sanity-codegen": "1.0.0-alpha.11"
  }

```

<img width="885" alt="Screenshot 2021-11-29 at 16 42 08" src="https://user-images.githubusercontent.com/33876435/143898530-ba2d0cd6-35cc-4b74-8927-c1816f2762d8.png">
<img width="1079" alt="Screenshot 2021-11-29 at 16 47 53" src="https://user-images.githubusercontent.com/33876435/143899022-1bbdf3be-ba83-4813-86af-3c8e56cf457f.png">

**Comment by andre-brdoch** [comment]
Hi @red-runner , you are right, this plugin is currently not compatible with the newest studio version. I will try to find some time in the next few days to fix it.

**Comment by andre-brdoch** [comment]
Hi @red-runner , if you install version `1.5.0` then it should work with any sanity studio version >= `2.22.0`

Thanks for bringing it up!
